apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: postgresql-state
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "host=db user=user password=password dbname=todo port=5432 sslmode=disable"
  - name: versionColumnType
    value: "version"